//
// Created by pablo on 11/29/24.
//

#ifndef ORTILIB_INCLUDE_ORWINDOW_ORWINDOW_ERRORS_H
#define ORTILIB_INCLUDE_ORWINDOW_ORWINDOW_ERRORS_H

enum ORWindowError {
    // Global
    OR_NO_ERROR = 0,
    OR_DISPLAY_CLIENT_INIT_FAILED,
    OR_DISPLAY_INIT_ERROR,
    // Wayland
    OR_WAYLAND_CLIENT_INIT_FAILED,
    OR_WAYLAND_SURFACE_INIT_ERROR,
    OR_WAYLAND_FAILED_WINDOW_SIZING,
    // Libdecor
    OR_LIBDECOR_INIT_ERROR,
    OR_LIBDECOR_FRAME_ERROR,
    OR_LIBDECOR_ERROR_CLEANING,
};

#endif // ORTILIB_INCLUDE_ORWINDOW_ORWINDOW_ERRORS_H
