//
// Created by pablo on 11/29/24.
//

#ifndef ORTILIB_INCLUDE_ORWINDOW_ORTIWINDOW_ERRORS_H
#define ORTILIB_INCLUDE_ORWINDOW_ORTIWINDOW_ERRORS_H

enum ORWindowError {
  OR_NO_ERROR = 0,
  OR_DISPLAY_INIT_ERROR,
  OR_WAYLAND_SURFACE_INIT_ERROR,
};

#endif //ORTILIB_INCLUDE_ORWINDOW_ORTIWINDOW_ERRORS_H
